ALTER TABLE "admins" ALTER COLUMN "nombre" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "admins" ALTER COLUMN "correo" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "admins" ALTER COLUMN "password" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "noticias" ALTER COLUMN "idAutor" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "noticias" ALTER COLUMN "titulo" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "noticias" ALTER COLUMN "contenido" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "noticias" ALTER COLUMN "fecha" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "noticias" ALTER COLUMN "ultimaEdicion" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "predecesoresPregunta" ALTER COLUMN "idPregunta" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "predecesoresPregunta" ALTER COLUMN "idRespuesta" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "preguntas" ALTER COLUMN "idSeccion" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "preguntas" ALTER COLUMN "pregunta" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "preguntas" ALTER COLUMN "orden" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "preguntas" ALTER COLUMN "idTipo" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "respuestas" ALTER COLUMN "idPregunta" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "respuestas" ALTER COLUMN "respuesta" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "respuestas" ALTER COLUMN "orden" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "respuestas" ALTER COLUMN "puntaje" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "resultados" ALTER COLUMN "idRespuesta" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "resultados" ALTER COLUMN "tipoUsuario" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "secciones" ALTER COLUMN "nombre" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "tiposPregunta" ALTER COLUMN "tipo" SET NOT NULL;